/**
 * Private/reviewer-beta explanation registry.
 *
 * This file is intentionally outside the anonymous public module graph. Copy
 * here may describe private routes, account workflow, incomplete backend
 * projections, and reviewer-only source semantics without making those strings
 * downloadable in the Free public artifact.
 */

import type { InfoNoteDefinition } from './info-note';

export const PRIVATE_INFO_NOTES = {
  'shell-notifications': {
    label: 'About account notifications',
    what: 'These messages report beta-account workflow changes such as access, cohort, or email-consent updates.',
    source: 'The admitted browser session requests a same-origin, session-scoped notification endpoint.',
    filedUnder: 'Account workflow · Notifications',
    review: 'The server writes and counts these account events; the browser validates the response before showing it.',
    lifecycle: 'Current state: the frontend is live and fail-closed; browser delivery remains unavailable until the backend accepts the beta session cookie.',
    limits: 'These are not civic Alerts. A denial, 404, outage, or invalid response means unavailable—not proof that no real events exist—and live mode never substitutes a sample.',
    expectedResult: 'A validated server list and server unread count, or a zero-badge unavailable explanation.',
  },
  'shell-account': {
    label: 'About the beta account context',
    what: 'The account chip identifies the private reviewer workspace, not a verified person or a paid plan.',
    source: 'A server-admitted beta session controls access before the shell is rendered.',
    filedUnder: 'Account workflow · Private beta session',
    review: 'Access must be rechecked server-side; browser copy never creates or proves identity, plan, team, or geography.',
    lifecycle: 'Current state: reviewer-beta account context. Detailed plan and team identity are incomplete.',
    limits: 'The chip contains no email address, legal identity, billing state, or entitlement decision.',
    expectedResult: 'A future account panel will show safe server-provided plan, team, geography, renewal, and support details.',
  },
  'shell-location': {
    label: 'About live scope and saved location',
    what: 'The location control opens place settings while preserving the server-authorized civic scope.',
    source: 'Live record scope comes from the reviewer response; a saved place label comes only from this browser.',
    filedUnder: 'Geography · Authorized scope and device view',
    review: 'The server must authorize each served geography. A device selection may narrow or label a view but cannot widen records.',
    lifecycle: 'Current state: live Alpine endpoint context with an optional device-local view label.',
    limits: 'A saved town is not residence, identity, coverage, entitlement, or permission to receive another location.',
    expectedResult: 'A server-backed place directory showing exactly which places are covered and when a location change is allowed.',
  },
  'shell-search': {
    label: 'About workspace search',
    what: 'Search sends the entered words to the Timeline route as a presentation filter.',
    source: 'Only fields already present in the authorized reviewer response are searched in the browser.',
    filedUnder: 'Workspace tools · Reviewed-record search',
    review: 'The filter never requests a wider lane, invents a relationship, or searches private source files.',
    lifecycle: 'Current state: live in-response text filter; cross-document and full-archive search are not connected.',
    limits: 'A missing match means no match in the current authorized response, not proof that the government record does not exist.',
    expectedResult: 'A reviewed search service with explicit population, filters, result counts, freshness, and source receipts.',
  },
  'shell-origin': {
    label: 'About the page data origin',
    what: 'The origin banner tells whether the current route is live server data, a reviewed archived snapshot, a synthetic design fixture, or illustrative product-demo media.',
    source: 'The route and build configuration select one explicit origin before content renders.',
    filedUnder: 'Data status · Origin and publication lane',
    review: 'Fixtures, snapshots, live reads, and product demos stay visibly distinct and are checked for public/private asset separation.',
    lifecycle: 'Current state: route-level origin indicator. Product-demo means admitted product education with hypothetical content, not a civic response.',
    limits: 'A reviewed snapshot is not live, a fixture is not civic evidence, a product demo is not a live or reviewed Alpine finding, and a live context may still contain incomplete projections.',
    expectedResult: 'Every page and export retains its exact source lane, generated time when supplied, and correction history.',
  },
  'shell-navigation': {
    label: 'About the workspace sections',
    what: 'The tabs organize the same authorized facts into agenda, timeline, body, power, source, briefing, watch, and alert workflows.',
    source: 'The application route registry defines each destination and its closest legacy alias.',
    filedUnder: 'Workspace navigation · Private beta',
    review: 'Opening a route never changes the session, plan, publication lane, geography grant, or authorized record IDs.',
    lifecycle: 'Current state: live route navigation; several destination tools remain detailed designed gaps.',
    limits: 'A visible tab does not promise that every backend projection or paid feature is available.',
    expectedResult: 'Stable route links with the same facts, context-sensitive tools, and explicit unavailable states.',
  },
  'shell-ai': {
    label: 'About AI-presented analysis',
    what: 'AI may help organize or explain reviewed material, but its output is not a primary source or official conclusion.',
    source: 'Only authorized record fields and source receipts may feed an AI-presented private explanation.',
    filedUnder: 'Method · AI assistance and human review',
    review: 'AI-presented material must stay labelled, preserve uncertainty, and remain traceable to exact reviewed receipts.',
    lifecycle: 'Current state: safety disclosure. Not every route currently uses AI-presented content.',
    limits: 'AI can be wrong and cannot grant access, verify a source, determine motive, provide legal advice, or replace human judgment.',
    expectedResult: 'Clearly labelled assistance with source comparison, uncertainty, reviewer decisions, and a correction route.',
  },
  'shell-print': {
    label: 'About print and PDF output',
    what: 'Print opens the browser print dialog for the currently visible route and mode.',
    source: 'The output is generated from the page already rendered in this browser.',
    filedUnder: 'Workspace tools · Local print or PDF',
    review: 'The application does not publish, email, archive, or certify the printed copy.',
    lifecycle: 'Current state: live browser print control in Simple mode.',
    limits: 'A printout can become stale, omit collapsed detail, and must not be treated as an official government record.',
    expectedResult: 'A dated export contract that preserves source receipts, data origin, access-safe fields, and correction notices.',
  },
  'beta-access': {
    label: 'About beta access status',
    what: 'This panel explains whether the current browser session may enter the private reviewer workspace.',
    source: 'A revocable server session and current allowlist decision are the production authority; local reviewer bypasses are walkthrough scaffolding only.',
    filedUnder: 'Account workflow · Beta admission',
    review: 'Pending, approved, denied, and revoked states are re-evaluated by the server and must remain indistinguishable from private civic data.',
    lifecycle: 'Current state: beta access workflow. Paid-plan and geographic entitlements are separate and incomplete.',
    limits: 'A URL, local storage value, visual mode, email form, or waitlist submission cannot grant reviewer access.',
    expectedResult: 'A secure sign-in and status flow that reveals no civic data until the server admits the session.',
  },
  'upload-overview': {
    // GOV-2256 — the Upload route's contextual guidance. Restores the closed #53
    // requirement (a purpose-specific note on every route/tool) for the intake
    // surface, and obeys the upload honesty contract: transfer ≠ processing,
    // receipt ≠ verification, no content before human review, fail-closed.
    label: 'About uploading a source file',
    what: 'This form sends a document you already have to a private review queue. Uploading a file here does not publish it, verify it, or add it as a civic source—it queues it for a reviewer to check.',
    source: 'The file, plus the two things you enter about it—where it came from and what kind of document it is—are sent over your admitted beta session to a same-origin intake endpoint. Your words are stored verbatim and describe the file, never a civic fact.',
    filedUnder: 'Account workflow · Private source intake',
    review: 'A person reviews every uploaded file before anything from it is shown or used. The browser never decides a file is trustworthy, and no content, quote, date, or name from it appears anywhere until that human review happens.',
    lifecycle: 'Current state: live intake for admitted reviewers. A confirmed upload reaches “received” or “held for additional review”; there is no verified, published, or trusted state you can reach from this form.',
    limits: 'The form shows which file types and size limit are accepted, and the server—not the browser—enforces them. A receipt confirms only that the file transferred for review; it is never a statement that the document is accurate, complete, official, or approved. If an upload cannot be confirmed, nothing is saved.',
    expectedResult: 'A queue receipt that the file was received for review, with the origin and kind you entered echoed back—or an honest error explaining that nothing was saved.',
  },
  'reviewer-context': {
    label: 'About the authorized reviewer record set',
    what: 'Every live private route reads the same memoized, server-authorized Alpine response for this app session.',
    source: 'One fixed same-origin reviewer endpoint supplies the validated record envelope.',
    filedUnder: 'Private data lane · Reviewer context',
    review: 'The entire response is shape-checked, path-screened, normalized, and rejected as a unit before any row renders.',
    lifecycle: 'Current state: live reviewer read when ready; loading, denied, unavailable, and invalid states fail closed with zero stale rows.',
    limits: 'Routes, filters, saved locations, and Simple/Advanced may narrow or rearrange the response but never add records or widen access.',
    expectedResult: 'One coherent authorized record set with stable IDs, trust labels, provenance, and source receipts across every route.',
  },
  'reviewed-record-trust': {
    label: 'About reviewed record labels',
    what: 'Status, verification, publication, correction, source-change, provenance, producer, speaker, and confidence labels describe one supplied record.',
    source: 'Values come from the validated backend response; the browser maps only documented codes to reader-facing text.',
    filedUnder: 'Civic records · Trust and provenance',
    review: 'Unknown or missing values remain unavailable. The client does not recompute confidence, publication, verification, or correction state.',
    lifecycle: 'Current state: live or reviewed-snapshot labels, depending on the page origin.',
    limits: 'A reviewed label is not a truth verdict, legal finding, motive judgment, completeness guarantee, or endorsement.',
    expectedResult: 'A consistent trust bundle whose definitions, source, update time, and correction history can be inspected.',
  },
  'reviewed-source-receipts': {
    label: 'About source receipts and locators',
    what: 'Receipts connect a reviewed statement to supplied source metadata, locators, archive state, and safe links.',
    source: 'Evidence entries in the authorized record carry source IDs, dates, relation types, page/section/time locators, and URLs when available.',
    filedUnder: 'Source Vault · Record receipts',
    review: 'Links and metadata are rendered only after web-safety checks; missing kinds remain absent rather than inferred.',
    lifecycle: 'Current state: live or reviewed-snapshot receipt metadata. Full source-registry health may still be unavailable.',
    limits: 'Link presence alone does not prove freshness, authenticity, completeness, preservation, or that the source supports every interpretation.',
    expectedResult: 'Open the exact original, archived, final, or supplied source and inspect validation and correction history.',
  },

  'home-overview': {
    label: 'About the Home overview',
    what: 'Home gives an everyday summary first and a denser research view without changing the underlying authorized facts.',
    source: 'The live version uses only the shared reviewer response; explicit design previews use visibly labelled fixtures.',
    filedUnder: 'Workspace · Home · Alpine',
    review: 'Both reading modes must enumerate the same record IDs and preserve every trust and source field.',
    lifecycle: 'Current state: live reviewed-record overview plus detailed planned projection slots.',
    limits: 'Home does not create agenda items, issues, newsletter stories, scores, verdicts, alerts, plans, or coverage decisions from statement text.',
    expectedResult: 'A quick civic briefing with direct receipts and clear links into deeper research tools.',
  },
  'home-summary': {
    label: 'How Home summary values are counted',
    what: 'The summary reports exact record rows, evidence receipt entries, response scope, and access lane in the current authorized response.',
    source: 'Counts and labels are read directly from the normalized reviewer-context object.',
    filedUnder: 'Home · Authorized response summary',
    review: 'Simple and Advanced must produce the same values; no hidden filter changes the totals.',
    lifecycle: 'Current state: live response summary, not a coverage, quality, activity, or performance score.',
    limits: 'Receipt count may include several entries for one source and the response population is not the full government archive.',
    expectedResult: 'Server-provided summary fields can replace local counting when a reviewed dashboard projection is available.',
    method: {
      version: 'HOME-RESPONSE-COUNT/v1',
      inputs: 'Validated StatementRecord rows and each row’s validated evidence array.',
      exclusions: 'Fixtures, rejected fields, cached prior responses, planned modules, and records outside the authorized response.',
      denominator: 'No percentage denominator is used; values are direct array counts or supplied labels.',
      cadence: 'Recomputed once when the shared reviewer response becomes ready for this app boot.',
      missingData: 'Missing arrays count as zero only for this response; zero does not claim the archive itself is empty.',
    },
  },
  'home-jurisdiction-filter': {
    label: 'About the Home jurisdiction filter',
    what: 'The filter changes which already-supplied preview items are shown for All, Town, County, or State.',
    source: 'Only explicit jurisdiction fields in the current reviewed snapshot or sample are eligible.',
    filedUnder: 'Home · Display filter · Government level',
    review: 'The control may narrow presentation and cannot assign an unknown record to a government level.',
    lifecycle: 'Current state: live display filter on preview sources; the live reviewer read model currently keeps its complete authorized set.',
    limits: 'An empty level means no matching supplied row, not proven absence of government activity or coverage.',
    expectedResult: 'A server-reviewed government-level field and consistent counts across Home, Timeline, Boards, and Location.',
  },
  'home-records': {
    label: 'About Home reviewed records',
    what: 'This section shows direct authorized statement rows and their source drawers before any higher-level product projection exists.',
    source: 'The shared reviewer-context response supplies the exact record order, IDs, labels, and evidence.',
    filedUnder: 'Home · Reviewed records and receipts',
    review: 'The same IDs must appear in both modes; detached or stale route loads cannot repaint the section.',
    lifecycle: 'Current state: live reviewer records when supplied; otherwise an honest detailed gap.',
    limits: 'A statement row is not automatically a meeting, agenda item, issue thread, official profile, alert, score, or newsletter story.',
    expectedResult: 'A concise summary backed by direct route links and exact receipts, while richer projections stay server-authored.',
  },
  'home-gaps': {
    label: 'About planned Home modules',
    what: 'These cards preserve the designed dashboard positions while documenting the exact backend contract each feature still needs.',
    source: 'Product design definitions and the absence of corresponding fields in the authorized reviewer response.',
    filedUnder: 'Home · Designed slots · Backend contracts',
    review: 'Each slot stays unavailable until its projection, access decision, geography, and publication lane are reviewed.',
    lifecycle: 'Current state: planned and incomplete. The cards contain explanations, not civic results.',
    limits: 'A polished placeholder does not prove data availability, entitlement, coverage, subscription, monitoring, or a release date.',
    expectedResult: 'The same positions will accept typed server projections without changing the information hierarchy or safety labels.',
  },
  'home-search': {
    label: 'About the planned 90-day Home search',
    what: 'This Simple-view tool is intended to search a defined recent window across supported civic record types.',
    source: 'A future reviewed archive index must define the searchable population, time basis, facets, and safe result fields.',
    filedUnder: 'Home · Search · Recent record window',
    review: 'The backend must return the window and count; the browser must not infer either from partial digest dates.',
    lifecycle: 'Current state: designed gap with disabled controls.',
    limits: 'No query runs, no 90-day completeness is claimed, and zero results are not displayed.',
    expectedResult: 'A fast recent-record search with exact scope, filters, counts, receipts, and missing-index explanation.',
  },
  'home-briefing': {
    label: 'About Home briefing stories',
    what: 'Briefing modules present saved newsletter items in plain language with status, AI, correction, and receipt labels intact.',
    source: 'A reviewed NewsletterDigest projection or an explicitly labelled archived digest snapshot.',
    filedUnder: 'Home · Civic briefing · Newsletter items',
    review: 'The website preserves backend order and labels instead of selecting a “featured” item from live statement text.',
    lifecycle: 'Current state: unavailable in the live reviewer response; archived preview data appears only in explicit snapshot/design modes.',
    limits: 'A summary is not an official notice and may be incomplete; its source trail remains the authority.',
    expectedResult: 'A versioned Alpine briefing with corrections, edition history, and direct source receipts.',
  },
  'home-accountability': {
    label: 'About Home accountability tools',
    what: 'These modules reserve space for source health, change tracking, promise/action review, and language-watch workflows.',
    source: 'Future reviewed source, comparison, alert, and verdict projections.',
    filedUnder: 'Home · Accountability workbench',
    review: 'Each conclusion requires typed inputs, exact receipts, method version, exclusions, reviewer state, and correction handling.',
    lifecycle: 'Current state: designed gaps; explicit fixtures remain visibly synthetic.',
    limits: 'No score, verdict, hidden-change claim, motive, or wording flag is inferred from ordinary statement rows.',
    expectedResult: 'Auditable research cards that explain what changed, why it was flagged, who reviewed it, and which receipts support it.',
  },
  'home-fast-agenda': {
    label: 'About the Home Fast Agenda module',
    what: 'This module gives a short next-meeting preview before the user opens the full agenda workspace.',
    source: 'A reviewed AgendaBoard projection; explicit preview mode may instead show labelled synthetic cards.',
    filedUnder: 'Home · Meetings and agendas',
    review: 'Only explicitly anchored agenda items may appear, and their supplied order and status stay unchanged.',
    lifecycle: 'Current state: live reviewer response lacks the projection; preview cards are synthetic and labelled.',
    limits: 'Statement rows are not converted into meetings, agenda items, deadlines, or likely decisions.',
    expectedResult: 'Three concise agenda items with meeting identity, official numbering, status, and exact packet receipts.',
  },
  'home-transparency-alerts': {
    label: 'About Home transparency alerts',
    what: 'This module will summarize reviewed document changes, missing media, corrections, and other source-backed transparency events.',
    source: 'A future reviewed transparency-alert projection; preview mode uses one clearly synthetic example.',
    filedUnder: 'Home · Transparency monitoring',
    review: 'A candidate needs typed before/after evidence and human-review state before display.',
    lifecycle: 'Current state: planned; no live alert row or alert count is connected.',
    limits: 'No source is accused of a late, hidden, missing, or quiet change from ordinary statement data.',
    expectedResult: 'A short reviewed alert list where every event opens its before/after receipts and review history.',
  },
  'home-active-issues': {
    label: 'About Home active issue rows',
    what: 'This module offers direct entry points into recently supplied reviewed records.',
    source: 'The reviewed card/feed projection in preview mode; the live read model exposes the same records directly instead.',
    filedUnder: 'Home · Reviewed activity',
    review: 'Rows keep their supplied IDs and labels and are not promoted into typed multi-record issue threads.',
    lifecycle: 'Current state: reviewed snapshot module in explicit preview; live Home uses the authorized record section.',
    limits: 'Recent activity, title similarity, or topic labels do not establish importance, issue membership, or government action.',
    expectedResult: 'Server-authored active issues with typed relationships, status, next action, and receipt-backed history.',
  },
  'home-timeline-preview': {
    label: 'About the Home Timeline preview',
    what: 'This module gives a small ordered sample of reviewed rows and links to the full Timeline.',
    source: 'The reviewed card/feed projection and its supplied ordering fields.',
    filedUnder: 'Home · Timeline preview',
    review: 'Trust, confidence, provenance, and receipt counts remain supplied and missing values are not invented.',
    lifecycle: 'Current state: reviewed snapshot module in explicit preview; live Home renders direct reviewer records.',
    limits: 'The displayed date may be an ordering aid, not a typed civic event date.',
    expectedResult: 'A concise typed event preview with explicit time meaning and direct source receipts.',
  },
  'home-source-vault': {
    label: 'About the Home Source Vault module',
    what: 'This module will summarize source freshness, preservation, validation, corrections, and receipt history.',
    source: 'A future source-registry summary; current preview may only mention receipt entries attached to digest items.',
    filedUnder: 'Home · Source Vault summary',
    review: 'Health and verification totals must be calculated by the reviewed registry service.',
    lifecycle: 'Current state: planned; source-health percentages and registry totals are unavailable.',
    limits: 'Receipt link count is not freshness, archive coverage, hash verification, or a complete registry population.',
    expectedResult: 'A source-health summary that opens exact receipt profiles and explains every incomplete or changed state.',
  },
  'home-latest-verdict': {
    label: 'About the Home latest-verdict slot',
    what: 'This slot will summarize one reviewed promise/action comparison while linking to its complete Power Tracker evidence.',
    source: 'A future saved promise/action verdict projection with canonical identity, quotes, actions, method, and receipts.',
    filedUnder: 'Home · Accountability · Promise/action review',
    review: 'A verdict requires method version, human review, uncertainty, challenge state, and correction history.',
    lifecycle: 'Current state: planned and unscored.',
    limits: 'Reviewed statements are not verdicts, and absence or text similarity is not kept/broken evidence.',
    expectedResult: 'A concise, challengeable result whose complete numerator, denominator, rationale, and receipts are inspectable.',
  },
  'home-language-watch': {
    label: 'About the Home Language Watch slot',
    what: 'This slot will surface exact source-anchored wording selected for human attention.',
    source: 'A future reviewed language-watch projection containing excerpt, locator, AI-presented label, and reviewer state.',
    filedUnder: 'Home · Research · Language Watch',
    review: 'AI may suggest wording, but a labelled saved review decision is required before presentation.',
    lifecycle: 'Current state: planned; no live wording flag is produced.',
    limits: 'The page does not infer intent, deception, legal effect, importance, or hidden meaning from ordinary text.',
    expectedResult: 'An exact excerpt with surrounding context, source receipt, reason for review, uncertainty, and correction path.',
  },
  'home-explainer': {
    label: 'About the Home explainer media slot',
    what: 'This module opens an accessible walkthrough of how sources, review, AI labels, corrections, Simple reading, and Advanced tools fit together.',
    source: 'An owner-supplied, versioned product-media asset, poster, and visual transcript. It does not come from the civic filing or reviewer-record pipeline.',
    filedUnder: 'Home · Product education',
    review: 'The exact video, poster, visible synthetic-data notice, transcript, links, and asset hashes are reviewed and released together.',
    lifecycle: 'Current state: available only inside the admitted private beta on the explicit illustrative-demo route.',
    limits: 'The video is silent and uses hypothetical records and figures. Neither it nor this Home card is a live finding, reviewed Alpine evidence, civic freshness claim, or authorization grant.',
    expectedResult: 'A responsive 1 minute 13 second native player with a poster, visible non-live-data notice, and complete visual text equivalent.',
  },
  'home-simple-things': {
    label: 'About the Home “things to know” list',
    what: 'This list presents a small number of saved briefing items without changing their review, AI, correction, or receipt labels.',
    source: 'A reviewed NewsletterDigest item order.',
    filedUnder: 'Home · Plain-language briefing',
    review: 'The browser does not rank live statement rows into “things to know.”',
    lifecycle: 'Current state: unavailable in the live reviewer response; preview snapshots preserve saved digest order.',
    limits: 'Inclusion is an editorial filing decision, not importance, endorsement, truth ranking, or complete civic coverage.',
    expectedResult: 'A versioned short briefing where each item opens its exact reviewed edition and receipts.',
  },
  'home-featured-story': {
    label: 'About the Home featured-story slot',
    what: 'This position gives one saved briefing item more reading space for summary, context, next action, and sources.',
    source: 'An explicitly selected item in a reviewed digest projection.',
    filedUnder: 'Home · Featured briefing',
    review: 'The live browser must not guess the featured item from response order or engagement.',
    lifecycle: 'Current state: unavailable live; snapshot preview uses saved digest order only as fixture-era presentation.',
    limits: 'A prominent position is not endorsement, importance score, official notice, or proof of completeness.',
    expectedResult: 'A backend-selected featured item with editorial rationale, version, correction state, and direct receipts.',
  },
  'home-edition-history': {
    label: 'About Home edition history',
    what: 'The selector will let readers compare saved newsletter editions and archived updates.',
    source: 'A future versioned digest archive with stable edition/version IDs and receipts.',
    filedUnder: 'Home · Newsletter history',
    review: 'Coverage periods are not treated as versions; selectors remain disabled until explicit version data exists.',
    lifecycle: 'Current state: planned and unavailable.',
    limits: 'No earlier edition, revision, change count, or current version is inferred.',
    expectedResult: 'Choose an edition version and inspect its publication time, changes, corrections, and source archive.',
  },
  'home-honesty-metrics': {
    label: 'How future publication-honesty metrics must work',
    what: 'Sourced, balanced, clear, and updated indicators will summarize defined publication metadata—not self-awarded quality claims.',
    source: 'A future reviewed digest-methodology projection with eligible items, source coverage, update/correction records, and editorial review fields.',
    filedUnder: 'Home · Publication methodology',
    review: 'Every metric needs a versioned formula, population, exclusions, denominator, cadence, and missing-data rule.',
    lifecycle: 'Current state: no metric or score is calculated.',
    limits: 'The site does not claim balance, clarity, sourcing, or timeliness from item count or its own interface copy.',
    expectedResult: 'Auditable metrics where every component and excluded/missing row is inspectable.',
    method: {
      version: 'Unavailable — publication metric methodology is not approved.',
      inputs: 'Future reviewed item/source/correction/update/editorial metadata.',
      exclusions: 'Undefined populations, incomplete source trails, unavailable versions, and unreviewed editorial classifications.',
      denominator: 'Unavailable until an eligible edition/item population is defined.',
      cadence: 'Unavailable; future values must include generated time and comparable method version.',
      missingData: 'Missing required inputs yield Metric unavailable, never zero or an estimated score.',
    },
  },
  'home-local-editions': {
    label: 'About County and State Home editions',
    what: 'These positions will show County and State briefings only when reviewed records and product coverage exist for those levels.',
    source: 'Future server-authorized geography plus level-specific reviewed briefing projections.',
    filedUnder: 'Home · Local editions · County and State',
    review: 'A response scope or empty local filter does not activate another geography.',
    lifecycle: 'Current state: planned honest-empty modules while the service focuses on Alpine.',
    limits: 'The placeholders do not claim County/State coverage, completeness, plan access, or expansion timing.',
    expectedResult: 'Authorized local editions with canonical place, coverage state, freshness, records, gaps, and exact receipts.',
  },

  'agenda-overview': {
    label: 'About Fast Agenda',
    what: 'Fast Agenda is the meeting-first view of notices, agenda items, packet changes, public-comment windows, decisions, and follow-up.',
    source: 'A reviewed AgendaBoard projection with stable meeting and agenda-item identifiers.',
    filedUnder: 'Civic records · Meetings and agendas · Alpine',
    review: 'The backend supplies order, lane, status, dates, and statement links; the browser never constructs agenda relationships from similar text.',
    lifecycle: 'Current state: detailed live contract gap; populated views are explicit samples or design fixtures.',
    limits: 'No meeting, agenda item, deadline, vote, status, or relationship is guessed from the statement feed.',
    expectedResult: 'A quick next-meeting read in Simple and a complete tracking board in Advanced over the same reviewed items.',
  },
  'agenda-meeting': {
    label: 'About agenda meeting context',
    what: 'Meeting date, body, title, and agenda item ID identify where a reviewed agenda card belongs.',
    source: 'Stable fields supplied together by the AgendaBoard response.',
    filedUnder: 'Fast Agenda · Meeting and item identity',
    review: 'A card is admitted only when the projection explicitly anchors it; unanchored statements stay outside the board.',
    lifecycle: 'Current state: populated only in explicit sample/design preview; live relationship projection is unavailable.',
    limits: 'A date embedded in an ID or source title is not enough to establish a meeting event.',
    expectedResult: 'Open an item-level view with official numbering, packet receipt, status history, and linked reviewed statements.',
  },
  'agenda-lifecycle': {
    label: 'About agenda lanes and status',
    what: 'Lanes organize reviewed items through the supplied agenda lifecycle; status badges preserve the backend’s current state.',
    source: 'AgendaBoard lane definitions, card lane IDs, labels, and status fields.',
    filedUnder: 'Fast Agenda · Lifecycle tracking',
    review: 'The page displays supplied states verbatim and does not predict a vote, outcome, or later step.',
    lifecycle: 'Current state: sample/design interaction contract; live Alpine board remains unavailable.',
    limits: 'A lane is a filing tool, not a truth verdict or guarantee that an event will happen.',
    expectedResult: 'Consistent item history with every transition, reviewer decision, timestamp, and source receipt.',
  },
  'agenda-filters': {
    label: 'About agenda filters and tools',
    what: 'Filters narrow already-reviewed meetings and item types; disabled tools show the intended handoff geometry.',
    source: 'Future typed AgendaBoard facets and the current explicit design-preview state.',
    filedUnder: 'Fast Agenda · Display and research tools',
    review: 'Unsupported controls stay disabled until the backend defines their population and exact field values.',
    lifecycle: 'Current state: incomplete; live route is a contract gap and design-preview tools are synthetic.',
    limits: 'A disabled control does not imply the underlying data exists or that an account is entitled to use it.',
    expectedResult: 'Filters with authoritative counts, reset behavior, saved views, and no change to the authorized record population.',
  },
  'agenda-sources': {
    label: 'About agenda source links and counts',
    what: 'Source links open the supplied meeting or item receipt; record counts describe explicitly anchored reviewed statements.',
    source: 'AgendaBoard sourceRefs and recordCount fields.',
    filedUnder: 'Fast Agenda · Item receipts',
    review: 'Missing links remain visibly missing and counts are never rebuilt from title similarity.',
    lifecycle: 'Current state: available only in explicit sample/design data until the live agenda projection exists.',
    limits: 'One source link does not establish completeness, final posting, or the meaning of a proposed action.',
    expectedResult: 'Exact packet versions, archive links, last-reviewed time, correction state, and linked statement receipts.',
  },
  'agenda-gaps': {
    label: 'About unavailable agenda features',
    what: 'Gap panels name the meeting, media, transcript, lineage, relationship, or decision contract that has not been supplied.',
    source: 'The designed Agenda workspace and the current response’s missing typed fields.',
    filedUnder: 'Fast Agenda · Designed gaps',
    review: 'A gap closes only after the server projection and access/publication policy are reviewed.',
    lifecycle: 'Current state: planned or incomplete, with zero substituted civic rows.',
    limits: 'The placeholder is not evidence of a meeting, missing record, deadline, decision, or government action.',
    expectedResult: 'A typed projection fills the same slot with exact source, review, freshness, and correction metadata.',
  },

  'timeline-overview': {
    label: 'About the Timeline',
    what: 'Timeline orders the authorized reviewed records and exposes the basis used for each placement.',
    source: 'The shared reviewer response plus documented ordering-date fields.',
    filedUnder: 'Civic records · Timeline · Alpine',
    review: 'The client may sort and filter supplied rows but never turns an ordering date into a typed civic event date.',
    lifecycle: 'Current state: live reviewed-record timeline with incomplete government-level and event projections.',
    limits: 'Order does not prove causation, relationship, publication time, meeting time, deadline, or issue membership.',
    expectedResult: 'A typed civic chronology with explicit event kinds, government levels, issue edges, and exact receipts.',
  },
  'timeline-filters': {
    label: 'About Timeline search and filters',
    what: 'Search, grouping, and record-type controls narrow or bucket records already in the authorized response.',
    source: 'Statement IDs/text, supplied speaker and agenda fields, and safe source metadata in the current response.',
    filedUnder: 'Timeline · Display filters',
    review: 'Invalid URL values fall back safely; Apply and Clear change only the route query and presentation.',
    lifecycle: 'Current state: live in-response filters. Unsupported event, issue, window, and sort tools remain disabled.',
    limits: 'A filtered-out row is still authorized, and zero matches do not prove absence from the full archive.',
    expectedResult: 'Server-supported facets with authoritative population, counts, saved views, and stable shareable URLs.',
  },
  'timeline-date-basis': {
    label: 'How Timeline ordering dates are chosen',
    what: 'Each row receives an ordering basis from an explicit precedence of agenda reference, source, capture/scan, validation, or evidence dates.',
    source: 'Only the date-like fields already present in the validated record and evidence entries.',
    filedUnder: 'Timeline · Derived ordering metadata',
    review: 'Every displayed basis remains labelled “not event” unless a future typed event projection says otherwise.',
    lifecycle: 'Current state: live client-derived ordering aid, not a civic-event calculation.',
    limits: 'The method does not infer publication, meeting, vote, deadline, effect, or causation.',
    expectedResult: 'Backend-supplied typed event time, timezone, meaning, source, and correction history.',
    method: {
      version: 'TIMELINE-ORDER/v1',
      inputs: 'Agenda-item reference date when valid; otherwise source_date, capture/scan, validation, or matching evidence-date fields.',
      exclusions: 'Free-text dates, file timestamps, URL text, ambiguous non-ISO values, and fields outside the authorized response.',
      denominator: 'No percentage denominator; one ordering basis is selected per record or the row remains Undated.',
      cadence: 'Recomputed on each Timeline render from the immutable normalized response.',
      missingData: 'A record with no eligible field remains Undated and is not placed on the proportional date bar.',
    },
  },
  'timeline-map': {
    label: 'How the Timeline date map is plotted',
    what: 'The map places dated reviewed rows proportionally between the earliest and latest eligible ordering dates.',
    source: 'The selected Timeline ordering dates and explicit government-level projection when available.',
    filedUnder: 'Timeline · Derived date map',
    review: 'Town, County, and State lanes stay unavailable unless a reviewed level relationship is supplied.',
    lifecycle: 'Current state: derived visual aid with incomplete government-level and connector data.',
    limits: 'Marker distance is not duration, importance, influence, causation, activity level, or event chronology.',
    expectedResult: 'A backend event map with typed times, levels, issue relationships, scale metadata, and receipt-linked markers.',
    method: {
      version: 'TIMELINE-MAP/v1',
      inputs: 'Eligible ordering dates after current route filters, with record and receipt counts.',
      exclusions: 'Undated rows, unsupported level assignments, inferred event types, and records outside the authorized response.',
      denominator: 'The inclusive span from the minimum to maximum eligible ordering date; a single-date set uses one centered position.',
      cadence: 'Recomputed after each local Timeline filter change.',
      missingData: 'Undated rows remain in the list but are not plotted; unavailable levels render explicit empty lanes.',
    },
  },
  'timeline-records': {
    label: 'About Timeline record cards',
    what: 'Cards show the ordered statement row, trust labels, completeness gaps, and evidence receipts without inventing an event.',
    source: 'Validated StatementRecord fields and their evidence arrays.',
    filedUnder: 'Timeline · Reviewed record lane',
    review: 'Trust, confidence, provenance, and completeness labels remain supplied or explicitly unavailable.',
    lifecycle: 'Current state: live reviewer rows; legacy/sample states are visibly separate.',
    limits: 'A card is not automatically an event, topic, issue thread, meeting item, official quote, or decision.',
    expectedResult: 'Typed event cards with direct record identity, relationships, corrections, and source provenance.',
  },
  'timeline-gaps': {
    label: 'About unavailable Timeline tools',
    what: 'Disabled level, event category, issue, window, sorting, lane, and connector tools preserve the planned research layout.',
    source: 'The design handoff and missing typed fields in the current reviewer contract.',
    filedUnder: 'Timeline · Designed gaps',
    review: 'Each control stays disabled until the backend supplies the field, population, safe values, and authorization.',
    lifecycle: 'Current state: incomplete and unavailable.',
    limits: 'Visible geometry does not claim coverage, data existence, entitlement, event meaning, or a release date.',
    expectedResult: 'Typed filters and connections whose counts and missing-data behavior are server-defined and testable.',
  },

  'boards-overview': {
    label: 'About the Boards directory',
    what: 'Boards is intended to organize government bodies, meetings, members, actions, issues, records, and watch tools.',
    source: 'The current live page has reviewed topic nodes and statement records but lacks a canonical government-body directory.',
    filedUnder: 'Government structure · Boards and bodies',
    review: 'Topic labels are never promoted to legal body identities without an explicit reviewed relationship.',
    lifecycle: 'Current state: live evidence context with detailed body-directory gaps.',
    limits: 'A topic, alias, source publisher, or mentioned office does not prove a board’s legal identity, membership, cadence, or authority.',
    expectedResult: 'A canonical Town/County/State body directory with stable IDs, official links, meetings, members, actions, and receipts.',
  },
  'boards-directory': {
    label: 'About Board directory levels and controls',
    what: 'Town, County, and State tabs will filter a canonical body directory once reviewed identities are supplied.',
    source: 'A future server projection of government bodies and their explicit jurisdiction hierarchy.',
    filedUnder: 'Boards · Government-level directory',
    review: 'Counts and tiles remain unavailable instead of being inferred from topics or statement mentions.',
    lifecycle: 'Current state: designed skeleton with unavailable metrics and controls.',
    limits: 'The current Alpine response scope is not enough to assign every record or topic to a specific legal body.',
    expectedResult: 'Authoritative body cards with office type, jurisdiction, cadence, membership, official URL, and data freshness.',
  },
  'boards-topic': {
    label: 'About reviewed topics on Boards',
    what: 'Topic context shows supplied concept-graph nodes and aliases while clearly separating them from government-body identity.',
    source: 'The reviewer response’s topic tree and explicit source locators.',
    filedUnder: 'Boards · Reviewed topic context',
    review: 'Requested topic IDs must match supplied nodes; unknown IDs do not create a page.',
    lifecycle: 'Current state: reviewed topic evidence, not a body directory.',
    limits: 'A topic rollup does not establish a department, board, official, meeting, vote, or legal authority.',
    expectedResult: 'Explicit typed links between topics, legal bodies, meetings, records, and source receipts.',
  },
  'boards-body': {
    label: 'About Board detail modules',
    what: 'Cadence, members, recent actions, active issues, source proof, and watch controls describe the intended body detail workspace.',
    source: 'Future canonical body, membership, meeting, action, issue, and monitoring projections.',
    filedUnder: 'Boards · Body detail',
    review: 'Every relationship needs a stable ID and reviewed source; the browser does not assemble it from labels.',
    lifecycle: 'Current state: planned modules shown as explicit contract gaps.',
    limits: 'No person, membership, meeting schedule, action, vote, or watch subscription is implied.',
    expectedResult: 'A sourced body profile with current and historical membership, meetings, actions, issues, and correction history.',
  },

  'issue-overview': {
    label: 'About Issue research',
    what: 'Issue detail opens one exact reviewed record and its proof rail without inventing a broader issue thread.',
    source: 'A stable statement ID selected from the authorized reviewer response.',
    filedUnder: 'Research · Record dossier',
    review: 'Unknown or missing IDs render an empty state; the first row is used only when no ID was requested.',
    lifecycle: 'Current state: live single-record dossier. Cross-record issue relationships are unavailable.',
    limits: 'One statement record is not a complete issue, official position, outcome, chronology, or policy analysis.',
    expectedResult: 'A typed issue dossier connecting proposals, actors, meetings, decisions, corrections, and exact receipts.',
  },
  'issue-trust': {
    label: 'About Issue trust and confidence fields',
    what: 'The trust bundle preserves supplied status, verification, publication, correction, source-change, provenance, producer, speaker, and confidence values.',
    source: 'The selected normalized StatementRecord.',
    filedUnder: 'Issue research · Trust bundle',
    review: 'The client maps known codes to labels and leaves missing values unavailable; it never calculates confidence.',
    lifecycle: 'Current state: live supplied metadata for this record.',
    limits: 'Confidence is not probability of truth, and status is not a verdict, legal conclusion, completeness guarantee, or endorsement.',
    expectedResult: 'Inspect definitions, reviewer decision, method provenance, update time, and correction history for each field.',
  },
  'issue-proof': {
    label: 'About the Issue proof rail',
    what: 'The proof rail lists each supplied evidence relation, locator, verification/correction metadata, and safe source link kind.',
    source: 'The selected record’s validated evidence array.',
    filedUnder: 'Issue research · Evidence and receipts',
    review: 'Duplicate URLs are collapsed within a receipt; missing links and metadata remain visibly absent.',
    lifecycle: 'Current state: live supplied receipt metadata or an honest empty source-trail state.',
    limits: 'A source link does not prove the full dossier is current, complete, independently verified, or correctly interpreted.',
    expectedResult: 'A complete claim-to-source map with archived versions, validation, corrections, and relationship review.',
  },
  'issue-missing': {
    label: 'About a missing Issue record',
    what: 'This state means the requested stable record ID is not present in the current authorized response.',
    source: 'The exact query ID and normalized response record IDs.',
    filedUnder: 'Issue research · Empty result',
    review: 'The page does not fall back to a similarly titled record or fixture.',
    lifecycle: 'Current state: honest empty for this response.',
    limits: 'Not present here does not prove the record never existed or is absent from every authorized archive.',
    expectedResult: 'A safe not-found explanation with links back to authorized search and Timeline results.',
  },

  'vault-overview': {
    label: 'About the Source Vault',
    what: 'Source Vault organizes the receipt metadata already attached to authorized records and preserves designed registry tools as honest gaps.',
    source: 'Evidence entries in the shared reviewer response.',
    filedUnder: 'Source Vault · Reviewed receipts',
    review: 'Rows are web-safety checked and deduplicated for this view; unsupported registry health is never inferred.',
    lifecycle: 'Current state: live receipt view with incomplete registry, version, ledger, media, alert, and verification projections.',
    limits: 'This is not the complete backend source registry, document store, archive manifest, or verification service.',
    expectedResult: 'A searchable, versioned source registry with validation, hashes, diffs, media status, alerts, and correction history.',
  },
  'vault-source-count': {
    label: 'How the Source Vault row count is calculated',
    what: 'The count represents unique receipt-metadata keys exposed by records in the current authorized response.',
    source: 'Each record’s evidence entries, deduplicated by a documented key precedence.',
    filedUnder: 'Source Vault · Current-response statistics',
    review: 'The value is recomputed from the immutable normalized response and is labelled as a partial receipt view.',
    lifecycle: 'Current state: live derived count, not a full registry count or coverage percentage.',
    limits: 'Several receipts may represent one underlying document, and fallback keys may keep otherwise-unidentified entries separate.',
    expectedResult: 'Server-supplied registry totals with exact population, exclusions, completeness, and generated time.',
    method: {
      version: 'VAULT-RECEIPT-DEDUP/v1',
      inputs: 'Validated evidence entries attached to authorized StatementRecord rows.',
      exclusions: 'Records outside the response, private paths, missing/rejected evidence, and registry objects not linked to these rows.',
      denominator: 'No percentage denominator. Key precedence is to_source_id, original_url, archive_url, then a per-record fallback.',
      cadence: 'Recomputed whenever Source Vault renders a newly ready reviewer response.',
      missingData: 'An unidentified receipt receives a per-record fallback key; zero means no receipt metadata in this response only.',
    },
  },
  'vault-filters': {
    label: 'About Source Vault search and filters',
    what: 'Search, source-type, and government-level controls are reserved for a defined full-registry population.',
    source: 'A future source-registry index with safe searchable fields and typed facets.',
    filedUnder: 'Source Vault · Registry filters',
    review: 'Controls remain disabled until the backend supplies authoritative facet values and counts.',
    lifecycle: 'Current state: designed gap with disabled inputs.',
    limits: 'The browser does not pretend the current receipt subset is a complete searchable vault.',
    expectedResult: 'Search and facets with authoritative population, match count, freshness, and reset/share behavior.',
  },
  'vault-source-rows': {
    label: 'About Source Vault receipt rows',
    what: 'Rows show supplied source ID, type, publisher, jurisdiction, date, validation time, and original/archive links.',
    source: 'Deduplicated validated evidence metadata in the current response.',
    filedUnder: 'Source Vault · Receipt rows',
    review: 'Missing values stay “not present”; no publisher, date, validation, or link is guessed.',
    lifecycle: 'Current state: live receipt metadata, not the source document content itself.',
    limits: 'A present link does not establish freshness, preservation, hash verification, or full claim support.',
    expectedResult: 'Open a stable source profile with versions, validation results, archive providers, related records, and corrections.',
  },
  'vault-diff': {
    label: 'About document version comparison',
    what: 'The version workspace will compare two reviewed copies and explain added, removed, and changed material.',
    source: 'A future source-versions projection containing exact version IDs, document text, locators, hashes, and deterministic diff output.',
    filedUnder: 'Source Vault · Document versions and diff',
    review: 'Both versions and the diff method must be reviewed; statement summaries are never used as substitute document text.',
    lifecycle: 'Current state: planned module with disabled selectors and geometry-only panes.',
    limits: 'No packet change, word change, silent edit, or legal effect is claimed.',
    expectedResult: 'A reproducible version comparison with page locators, change log, timestamps, hashes, and review state.',
  },
  'vault-ledger': {
    label: 'About Source Vault ledger history',
    what: 'The ledger will show first seen, versions, validations, manifest hashes, corrections, and archive events for a source.',
    source: 'A future append-only reviewed source-ledger projection.',
    filedUnder: 'Source Vault · Provenance ledger',
    review: 'Every event needs a stable source/version ID, canonical time, actor/process provenance, and safe receipt.',
    lifecycle: 'Current state: planned; all ledger fields and tools are unavailable.',
    limits: 'Receipt dates are not substituted for first-seen or version history.',
    expectedResult: 'An auditable source lifecycle with immutable event ordering and correction links.',
  },
  'vault-video': {
    label: 'About video and transcript status',
    what: 'The media ladder will distinguish pending release, pending transcript, missing media, and available reviewed assets.',
    source: 'A future typed media-status projection tied to a meeting/source identity.',
    filedUnder: 'Source Vault · Video and transcript',
    review: 'A state must be supplied with timestamp, source, and review status; source dates do not imply media availability.',
    lifecycle: 'Current state: geometry-only planned states.',
    limits: 'No video is claimed missing, withheld, late, released, or transcribed.',
    expectedResult: 'Accessible video, captions, transcript, release history, missing-record explanation, and exact source receipts.',
  },
  'vault-transparency': {
    label: 'About Source Vault transparency alerts',
    what: 'This tool will list reviewed source changes, missing records, validation failures, and later-cleared flags.',
    source: 'A future reviewed transparency-alert projection.',
    filedUnder: 'Source Vault · Transparency monitoring',
    review: 'Candidate changes require typed comparison evidence and review before becoming an alert.',
    lifecycle: 'Current state: planned; no live alert generation or count occurs on this page.',
    limits: 'Statement status, missing links, or dates are not converted into transparency accusations.',
    expectedResult: 'Open and cleared alerts with reason, severity, timestamps, review decisions, and before/after receipts.',
  },
  'vault-verification': {
    label: 'About source verification details',
    what: 'Verification distinguishes link presence from archive-provider validation, file hashes, and manifest completeness.',
    source: 'Current link counts come from receipt metadata; stronger claims require a reviewed registry verification projection.',
    filedUnder: 'Source Vault · Verification',
    review: 'Unavailable third-party status and manifest hash remain explicit; browser tools stay disabled.',
    lifecycle: 'Current state: link-presence diagnostics only; independent verification and manifest hashing are unavailable.',
    limits: 'An original or archive URL is not a successful fetch, preserved snapshot, authentic file, matching hash, or complete manifest.',
    expectedResult: 'Provider results, validation time, immutable manifest population, SHA-256 values, failures, and recheck history.',
    method: {
      version: 'VAULT-LINK-PRESENCE/v1',
      inputs: 'Deduplicated receipt rows with non-empty original_url or archive_url fields.',
      exclusions: 'Final/source URLs, failed fetch state, private paths, and documents outside the current response.',
      denominator: 'Counts are absolute link-presence totals; no verification percentage denominator is available.',
      cadence: 'Recomputed when the current reviewer response renders.',
      missingData: 'Missing URLs remain absent and do not count as verified, failed, or missing-source alerts.',
    },
  },

  'newsletter-overview': {
    label: 'About the Newsletter',
    what: 'Newsletter turns reviewed civic activity into versioned plain-language editions while preserving source and correction labels.',
    source: 'A server-reviewed NewsletterDigest projection; archived snapshots appear only behind an explicit snapshot route.',
    filedUnder: 'Publications · Civic newsletter · Alpine',
    review: 'The backend selects, orders, labels, and versions items; the browser does not guess a current or featured edition.',
    lifecycle: 'Current state: live detailed contract gap. Archived digest views are reviewer-only snapshots, not live reads.',
    limits: 'A digest is not an official notice, complete archive, legal advice, or substitute for its primary records.',
    expectedResult: 'A searchable archive and edition detail page with coverage dates, corrections, trust labels, and one-tap receipts.',
  },
  'newsletter-archive': {
    label: 'About newsletter archive rows',
    what: 'Archive rows identify saved editions by stable ID, coverage period, publication state, and item count.',
    source: 'The supplied NewsletterDigestResponse.',
    filedUnder: 'Newsletter · Edition archive',
    review: 'No edition is called current or featured unless the projection explicitly marks it.',
    lifecycle: 'Current state: reviewed archived snapshot when explicitly requested; live archive projection is unavailable.',
    limits: 'Coverage dates are not version history, freshness, or proof the period is complete.',
    expectedResult: 'Versioned archive rows with generated/published time, correction state, audience, and exact edition receipts.',
  },
  'newsletter-edition': {
    label: 'About a newsletter edition',
    what: 'Edition detail preserves ordered sections, reviewed summaries, labels, coverage dates, and source trails.',
    source: 'One digest selected by exact stable edition ID.',
    filedUnder: 'Newsletter · Edition detail',
    review: 'Unknown IDs render a safe empty state; item order and section membership are not recomputed.',
    lifecycle: 'Current state: reviewer archived snapshot only.',
    limits: 'The page does not claim the snapshot is current, owner-published, complete, or safe for public release.',
    expectedResult: 'A published edition with version/correction history and direct links to each supporting civic record.',
  },
  'newsletter-sections': {
    label: 'About newsletter section filing',
    what: 'Sections group digest items by explicit backend keys such as agenda, decisions, changes, follow-up, and source notes.',
    source: 'The digest’s saved section IDs and item references.',
    filedUnder: 'Newsletter · Editorial structure',
    review: 'Missing sections remain empty; the client does not classify statement text into an editorial category.',
    lifecycle: 'Current state: archived snapshot structure; several designed sections may be honest-empty.',
    limits: 'Section placement is an editorial filing decision, not importance, truth, endorsement, or completeness.',
    expectedResult: 'Reviewed editorial structure with rationale, item provenance, corrections, and accessible reading order.',
  },
  'newsletter-trust': {
    label: 'About newsletter claim and AI labels',
    what: 'Claim status, correction, speaker, and AI-presented labels preserve how each digest item was reviewed.',
    source: 'Saved item label fields in the NewsletterDigest projection.',
    filedUnder: 'Newsletter · Item trust and presentation',
    review: 'Known codes map to approved tones; missing speaker or confidence remains explicitly unavailable.',
    lifecycle: 'Current state: reviewed snapshot metadata.',
    limits: 'AI-presented text can be wrong, and a claim label is not a legal or political verdict.',
    expectedResult: 'Every summary shows its review state, exact receipts, correction history, and human-readable label definitions.',
  },
  'newsletter-gaps': {
    label: 'About unavailable newsletter modules',
    what: 'Gap modules reserve positions for filters, edition diffs, delivery, questions, methodology, and other designed briefing tools.',
    source: 'The design baseline and missing fields in the current digest/reviewer contracts.',
    filedUnder: 'Newsletter · Designed gaps',
    review: 'Each module stays disabled or explanatory until a typed reviewed projection and access decision exist.',
    lifecycle: 'Current state: planned or incomplete.',
    limits: 'No subscription, send, current-edition claim, content comparison, or reader question workflow is active.',
    expectedResult: 'Versioned briefings, deterministic edition diffs, delivery preferences, and sourced reader research tools.',
  },

  'power-overview': {
    label: 'About the Power Tracker',
    what: 'Power Tracker is the planned evidence workbench for officials, roles, quotes, promises, actions, votes, and reviewed comparisons.',
    source: 'Current direct records supply evidence only; official identities and comparison ledgers require separate reviewed projections.',
    filedUnder: 'Research · Power and accountability',
    review: 'No person, office, promise, action, match, verdict, or score appears without stable identity and exact receipts.',
    lifecycle: 'Current state: live reviewed evidence rows plus explicit unavailable tool contracts; populated people are synthetic fixtures only.',
    limits: 'The page does not infer motive, influence, ideology, performance, promise status, or official identity from statement text.',
    expectedResult: 'Sourced official profiles and auditable promise/action research with consent, challenge, method, and correction history.',
  },
  'power-jurisdiction': {
    label: 'About Power Tracker jurisdiction filters',
    what: 'Town, County, and State controls will narrow an explicit reviewed official roster.',
    source: 'A future official directory with canonical person, office, role, term, and jurisdiction IDs.',
    filedUnder: 'Power Tracker · Government level',
    review: 'Controls stay unavailable when the roster or exact level relationship is absent.',
    lifecycle: 'Current state: designed filter geometry; fixture choices affect synthetic people only.',
    limits: 'Alpine response scope and source publisher names do not establish an official’s jurisdiction.',
    expectedResult: 'Authoritative roster filtering with counts, term history, office changes, and source provenance.',
  },
  'power-roster': {
    label: 'About official roster and profiles',
    what: 'Roster/profile modules will identify an official, office, role, term, jurisdiction, and policy-cleared official links.',
    source: 'A future reviewed official-identity and office-history projection.',
    filedUnder: 'Power Tracker · Officials and offices',
    review: 'Identity needs stable IDs and source receipts; names in statements are never promoted automatically.',
    lifecycle: 'Current state: unavailable in live data; placeholder people in design mode are synthetic.',
    limits: 'No displayed placeholder represents a real person, verified identity, office holder, or political affiliation.',
    expectedResult: 'Canonical profiles with role/term history, source proof, corrections, and linked reviewed actions.',
  },
  'power-score': {
    label: 'How future Power scores must be calculated',
    what: 'Kept, broken, pending, and any summary score may appear only after reviewed promises are matched to typed actions under a versioned method.',
    source: 'Future promise, action, vote, outcome, identity, and receipt projections plus a saved human review decision.',
    filedUnder: 'Power Tracker · Methodology and score',
    review: 'The method version, match evidence, exclusions, challenge state, and correction history must be visible with every result.',
    lifecycle: 'Current state: no live score or denominator exists; design numbers are synthetic and visibly fixture-only.',
    limits: 'No statement, absence, delay, vote, or text similarity is automatically classified as kept, broken, partial, or pending.',
    expectedResult: 'An auditable calculation where every numerator/denominator row opens the promise, action, receipts, review, and appeal.',
    method: {
      version: 'Unavailable — a methodology must be owner-approved before production use.',
      inputs: 'Canonical official identity, exact promise quote, typed action/outcome, dates, jurisdiction, source receipts, and saved review decision.',
      exclusions: 'Ambiguous identity, aspirational/non-commitment language, missing action coverage, out-of-scope jurisdiction, and unresolved receipt conflicts.',
      denominator: 'Unavailable. No eligible-promise population has been defined or reviewed.',
      cadence: 'Unavailable. A future method must state review and recalculation timing.',
      missingData: 'Missing or disputed inputs produce unavailable/pending review, never a negative score.',
    },
  },
  'power-match': {
    label: 'About promise and action matching',
    what: 'A match compares one exact promise with a typed later action or outcome and preserves AI disclosure, reviewer consent, and challenge controls.',
    source: 'Future canonical promise/action rows with exact quote and action receipts.',
    filedUnder: 'Power Tracker · Promise/action review',
    review: 'AI may suggest a candidate, but a saved reviewer decision and challenge path are required before presentation as a reviewed match.',
    lifecycle: 'Current state: unavailable in live data; fixture modal demonstrates interaction only.',
    limits: 'Similarity is not proof of identity, intent, fulfillment, contradiction, causation, or final outcome.',
    expectedResult: 'A consent-first comparison with side-by-side receipts, rationale, uncertainty, review history, and correction/challenge resolution.',
  },
  'power-ledgers': {
    label: 'About quote, promise, vote, and action ledgers',
    what: 'Ledgers will separate verbatim quotes, commitments, recorded votes, official actions, outcomes, and their source trails.',
    source: 'Future typed ledger projections with canonical identities, stable row IDs, dates, relation types, and receipts.',
    filedUnder: 'Power Tracker · Evidence ledgers',
    review: 'Rows need speaker-safe attribution and explicit type; statement records are not relabelled as quotes, promises, votes, or actions.',
    lifecycle: 'Current state: planned table geometry with unavailable rows.',
    limits: 'Empty ledgers do not prove an official made no statement, promise, vote, or action.',
    expectedResult: 'Searchable ledgers with corrections, conflicts, missing-record flags, and direct primary-source links.',
  },

  'watchlist-overview': {
    label: 'About the Watchlist',
    what: 'Watchlist is a personal reading list for authorized record keys and future monitoring tools.',
    source: 'Today’s selected keys are stored only in this browser and matched against the current reviewer response.',
    filedUnder: 'Personal workspace · Watchlist',
    review: 'Only exact authorized IDs reveal record detail; unknown keys remain opaque.',
    lifecycle: 'Current state: device-local reading list. Server sync, monitoring, deadlines, history, and delivery are unavailable.',
    limits: 'Tracking a key does not create a subscription, alert, reminder, background monitor, team share, or cross-device state.',
    expectedResult: 'A server-backed list with explicit owner/team scope, monitoring rules, deadlines, alerts, history, and revocation.',
  },
  'watchlist-local-state': {
    label: 'About device-local Watchlist state',
    what: 'Add and remove controls change only the set of stored record keys in this browser.',
    source: 'Local storage plus exact IDs from the current authorized response.',
    filedUnder: 'Watchlist · Device preference',
    review: 'The page intersects stored keys with authorized IDs before showing any civic detail.',
    lifecycle: 'Current state: live local interaction; data does not sync to an account.',
    limits: 'Clearing browser storage loses the list, and an unmatched key is not evidence of a record or access.',
    expectedResult: 'Authenticated, encrypted server sync with audit history, team ownership, retention, export, and deletion controls.',
  },
  'watchlist-add': {
    label: 'About adding Watchlist items',
    what: 'Candidate controls add one exact authorized record ID to this browser’s local list.',
    source: 'The current reviewer response supplies the candidate IDs.',
    filedUnder: 'Watchlist · Add or remove',
    review: 'Duplicates remain idempotent and removal does not alter the underlying civic record.',
    lifecycle: 'Current state: live device-local control; unsupported record types remain unavailable.',
    limits: 'Adding an item does not contact a person, modify a source, request coverage, or enable monitoring.',
    expectedResult: 'Add statements, bodies, officials, documents, issues, or searches with server-confirmed type and access.',
  },
  'watchlist-timing': {
    label: 'About Watchlist next events and deadlines',
    what: 'Timing fields are reserved for typed future events, deadlines, and review status connected to a watched entity.',
    source: 'A future event/deadline projection with stable relationship IDs and source receipts.',
    filedUnder: 'Watchlist · Timing and follow-up',
    review: 'No date is inferred from agenda IDs, source dates, or statement wording.',
    lifecycle: 'Current state: unavailable.',
    limits: 'An empty timing field does not mean nothing is scheduled or no deadline exists.',
    expectedResult: 'Source-backed next event, deadline, timezone, update history, and missing-data warning.',
  },
  'watchlist-record-types': {
    label: 'About Watchlist record types',
    what: 'Type controls describe planned support for statements, boards, officials, documents, issues, and other stable entities.',
    source: 'Future canonical entity IDs and authorization-aware type projections.',
    filedUnder: 'Watchlist · Supported entity types',
    review: 'A type activates only when its identity and watch behavior are defined end to end.',
    lifecycle: 'Current state: statement IDs only; other controls are designed gaps or fixture geometry.',
    limits: 'A disabled type does not imply the entity exists or the account is entitled to monitor it.',
    expectedResult: 'Typed watch entries with appropriate route, title, source, ownership, and monitoring options.',
  },
  'watchlist-delivery': {
    label: 'About Watchlist monitoring and delivery',
    what: 'History, triggers, email/text/push, reminders, and digest settings belong to a future server monitoring service.',
    source: 'Future watch-rule, recipient, consent, event, and delivery-receipt projections.',
    filedUnder: 'Watchlist · Monitoring and delivery',
    review: 'Recipients and event rules must be verified; every delivery needs status and retry history.',
    lifecycle: 'Current state: unavailable. Device-local keys are not monitored.',
    limits: 'The interface makes no speed, delivery, meeting-eve, daily digest, or reliability promise.',
    expectedResult: 'Explicit rules and recipient consent with event receipts, delivery status, retries, quiet hours, and unsubscribe controls.',
  },

  'location-overview': {
    label: 'About the Location workspace',
    what: 'Location separates a device-selected place from server-authorized civic scope, coverage, and account geography.',
    source: 'The reviewer response supplies live scope; local storage supplies an optional reading preference.',
    filedUnder: 'Geography · Location and coverage',
    review: 'A place becomes serviceable only after canonical identity, record binding, source health, publication lane, and account grant are reviewed.',
    lifecycle: 'Current state: live Alpine scope plus device-local selection; directories and coverage projections are incomplete.',
    limits: 'Selecting a place does not prove residence, identity, plan, coverage, border-town relationship, or permission to receive its records.',
    expectedResult: 'A canonical hierarchy showing covered Town/County/State areas, grant limits, source health, and change policy.',
  },
  'location-saved-scope': {
    label: 'About saved place versus official scope',
    what: 'The saved label changes the local view while live records remain bound to the server response’s authorized Alpine scope.',
    source: 'Local storage for the label and the reviewer response for civic records.',
    filedUnder: 'Location · Device view and authorized scope',
    review: 'A non-Alpine saved selection narrows the page to zero civic rows rather than relabelling Alpine records.',
    lifecycle: 'Current state: live safety boundary.',
    limits: 'The device label is not a canonical place ID, account home, eligibility decision, or coverage grant.',
    expectedResult: 'Server-resolved place IDs with an explicit authorized/saved comparison and safe switch behavior.',
  },
  'location-directory': {
    label: 'About the State, County, and Town directory',
    what: 'Hierarchy controls will navigate canonical states, counties, regions, towns, and approved border relationships.',
    source: 'A future reviewed location-directory projection with stable IDs and parent/neighbor edges.',
    filedUnder: 'Location · Canonical directory',
    review: 'Controls and tiles stay disabled until identity, hierarchy, serving state, and safe labels are supplied.',
    lifecycle: 'Current state: planned directory geometry; fixture selectors are synthetic.',
    limits: 'A text label or neighboring town does not establish a legal hierarchy, border, source coverage, or entitlement.',
    expectedResult: 'Searchable canonical places with official names, IDs, hierarchy, coverage state, and source-health summary.',
  },
  'location-coverage': {
    label: 'How future location coverage must be calculated',
    what: 'Coverage will report how much of a defined eligible source/record population is current and review-ready for each place.',
    source: 'Future canonical place, source registry, processing backlog, freshness, and publication projections.',
    filedUnder: 'Location · Coverage diagnostics',
    review: 'Every percentage must disclose method version, population, numerator, denominator, exclusions, generated time, and missing-data behavior.',
    lifecycle: 'Current state: no live coverage percentage exists; design-preview percentages are synthetic geometry only.',
    limits: 'The page does not infer coverage from current statement count, receipt count, scope label, or a selected place.',
    expectedResult: 'Auditable Town/County/State coverage with freshness, backlog, missing sources, trends, and correction history.',
    method: {
      version: 'Unavailable — coverage methodology is not approved or connected.',
      inputs: 'Canonical place IDs, eligible source registry, expected records, processed/validated state, freshness windows, and publication eligibility.',
      exclusions: 'Out-of-scope sources, duplicate versions, private-only material, unresolved identity, and policy-excluded records.',
      denominator: 'Unavailable. The eligible source/record population has not been supplied.',
      cadence: 'Unavailable. A future projection must supply generated time and refresh policy.',
      missingData: 'Missing population or validation data yields Coverage unavailable, never zero or an estimated percentage.',
    },
  },
  'location-change-policy': {
    label: 'About home-place and change policy',
    what: 'This module will explain the account’s primary town, included border towns, and when an allowed town change may occur.',
    source: 'A future server-authoritative plan and exact-geography assignment decision.',
    filedUnder: 'Account geography · Home and change policy',
    review: 'Changes require a saved server decision with actor, operation ID, effective time, and prior assignment history.',
    lifecycle: 'Current state: unavailable. The browser stores no authoritative home-town assignment.',
    limits: 'A local picker cannot start, accelerate, bypass, or prove a three-month change window.',
    expectedResult: 'A clear assignment map, eligible border towns, next change date, consequences, and confirmation workflow.',
  },
  'location-history': {
    label: 'About coverage history and backlog',
    what: 'History will show source freshness, processing backlog, coverage changes, funding/operational notes, and reviewed trend context.',
    source: 'Future dated coverage snapshots and operational metrics bound to a canonical place.',
    filedUnder: 'Location · Coverage history',
    review: 'Trends require comparable method versions and denominators; method changes must be visible.',
    lifecycle: 'Current state: planned and unavailable.',
    limits: 'No processing speed, improvement, decline, cause, or funding conclusion is inferred.',
    expectedResult: 'Versioned coverage history with comparable metrics, annotations, gaps, and source provenance.',
  },

  'alerts-overview': {
    label: 'About civic Alerts',
    what: 'Alerts will report reviewed civic events such as agenda posting, source changes, deadlines, votes, missing media, and follow-up.',
    source: 'A future civic-alert projection with typed events, stable IDs, exact receipts, timestamps, and review state.',
    filedUnder: 'Monitoring · Civic Alerts',
    review: 'Candidate events require backend detection and review before appearing or being delivered.',
    lifecycle: 'Current state: live page is an honest unavailable workspace; design cards are synthetic and device-only.',
    limits: 'Civic Alerts are separate from account-workflow notifications. Statement rows and account messages are never substituted.',
    expectedResult: 'A sourced civic inbox with read state, history, triggers, delivery preferences, freshness, and correction handling.',
  },
  'alerts-feed': {
    label: 'About the civic alert feed',
    what: 'Each alert row will carry severity, government level, event type, explanation, source receipt, stable ID, event time, freshness, and read state.',
    source: 'A future authorized civic-alert endpoint.',
    filedUnder: 'Alerts · Reviewed event feed',
    review: 'The complete row schema is validated before display; malformed or unauthorized events fail closed.',
    lifecycle: 'Current state: feed not connected and zero civic rows rendered.',
    limits: 'Unavailable is not proof of zero events, and no statement/account notification becomes a civic alert.',
    expectedResult: 'A trustworthy new/earlier feed where every alert opens the exact affected record and receipt.',
  },
  'alerts-read-state': {
    label: 'How alert unread state must work',
    what: 'Unread count and mark-one/all controls will reflect server-owned state for stable civic alert IDs.',
    source: 'A future session-scoped alert response and read-state mutation contract.',
    filedUnder: 'Alerts · Read state',
    review: 'The server count is authoritative and mutations require idempotent ownership checks.',
    lifecycle: 'Current state: unavailable in live data; fixture read state is stored only on this device.',
    limits: 'The page does not display an invented zero unread count when the feed is unavailable.',
    expectedResult: 'Consistent own-account read state across devices with audit-safe retries and no cross-user rows.',
    method: {
      version: 'Unavailable for live civic Alerts; fixture interaction uses ALERT-DEMO-LOCAL/v1.',
      inputs: 'Stable alert IDs and server read booleans; fixture mode uses explicit synthetic IDs in local storage.',
      exclusions: 'Account notifications, statement rows, malformed IDs, unauthorized events, and unavailable responses.',
      denominator: 'All authorized alert rows returned by the server for the unread count.',
      cadence: 'Server count on each feed response; fixture count on each local read-state change.',
      missingData: 'Unavailable feed means Count unavailable and no mark-read action, never an assumed zero.',
    },
  },
  'alerts-triggers': {
    label: 'About civic alert trigger rules',
    what: 'Trigger categories describe which reviewed events may create alerts for watched entities and places.',
    source: 'Future typed event producers and saved watch-rule definitions.',
    filedUnder: 'Alerts · Trigger policy',
    review: 'Each rule needs explicit event type, scope, source requirements, deduplication, severity, and reviewer policy.',
    lifecycle: 'Current state: planned checklist; every live trigger is disabled.',
    limits: 'Checking a design control does not register monitoring or claim that an event producer exists.',
    expectedResult: 'User-visible rules with exact scope, event receipts, quieting/deduplication, history, and revoke controls.',
  },
  'alerts-delivery': {
    label: 'About alert delivery settings',
    what: 'Email, text, push, meeting-eve, and digest options will control verified-recipient delivery for civic alerts.',
    source: 'Future recipient, consent, preference, event, and delivery-receipt contracts.',
    filedUnder: 'Alerts · Delivery and consent',
    review: 'Recipient verification, opt-in, retries, failures, quiet hours, and unsubscribe must be enforced server-side.',
    lifecycle: 'Current state: unavailable; fixture toggles update only this browser and send nothing.',
    limits: 'No channel, timing, reliability, speed, reminder, or digest promise is active.',
    expectedResult: 'Consent-based delivery with status, timestamps, retries, suppression, and unsubscribe history.',
  },
  'alerts-tracking': {
    label: 'About tracked-item alert diagnostics',
    what: 'This diagnostic counts local Watchlist keys that exactly match records in the current response.',
    source: 'Device-local watch keys intersected with authorized statement IDs.',
    filedUnder: 'Alerts · Local diagnostics',
    review: 'Matching reveals only already-authorized IDs and does not register a backend rule.',
    lifecycle: 'Current state: live local diagnostic, not monitoring.',
    limits: 'A matching count does not mean alerts, subscriptions, delivery, deadlines, or background checks are active.',
    expectedResult: 'Server-backed watch rules showing scope, event types, last check, next check, delivery, and failures.',
    method: {
      version: 'ALERT-WATCH-INTERSECTION/v1',
      inputs: 'Local watchlist keys and exact authorized StatementRecord IDs.',
      exclusions: 'Unknown keys, unauthorized records, non-statement entity types, account notifications, and fixtures outside explicit demo mode.',
      denominator: 'No percentage denominator; the result is the number of exact matching IDs.',
      cadence: 'Recomputed when Alerts renders from the current response and current local storage.',
      missingData: 'Missing/invalid storage is an empty local key set and still does not claim server monitoring state.',
    },
  },
  'alerts-freshness': {
    label: 'About alert time and freshness',
    what: 'Event time, generated time, source freshness, and delivery time describe different stages of an alert.',
    source: 'A future civic-alert response and its exact source/delivery receipts.',
    filedUnder: 'Alerts · Time and freshness',
    review: 'Every timestamp needs a defined meaning and UTC value; one timestamp is never substituted for another.',
    lifecycle: 'Current state: unavailable.',
    limits: 'Source dates, validation dates, and browser time do not prove when a civic event happened or an alert was delivered.',
    expectedResult: 'Clearly separated event, detection, review, generation, delivery, and read times with stale-data warnings.',
  },

  'topics-overview': {
    label: 'About the Topics tree',
    what: 'Topics groups reviewed concept nodes and aliases supplied by the backend and lets users focus the tree.',
    source: 'The authorized topic_tree projection and explicit rollup edges.',
    filedUnder: 'Research · Topics and concept graph',
    review: 'Moves and deeper relationships remain demo-only unless saved and reviewed by the backend.',
    lifecycle: 'Current state: reviewed topic tree when supplied; missing relationships render detailed gaps.',
    limits: 'A topic edge is not causation, government-body identity, issue membership, or policy conclusion.',
    expectedResult: 'A reviewed concept graph with provenance, aliases, body/meeting/record links, corrections, and audited editing.',
  },
  'body-overview': {
    label: 'About Government Body context',
    what: 'This route will connect one canonical government body to its meetings, records, members, actions, issues, and receipts.',
    source: 'Current direct records plus a future explicit body-to-record relationship projection.',
    filedUnder: 'Government structure · Body detail',
    review: 'Direct records remain labelled unscoped until a stable body relationship is supplied.',
    lifecycle: 'Current state: relationship gap with direct authorized records only.',
    limits: 'Route labels, source publishers, topics, or statement mentions do not establish body ownership.',
    expectedResult: 'A sourced canonical body page with legal identity, jurisdiction, meetings, membership, actions, and correction history.',
  },
  'meeting-overview': {
    label: 'About Meeting context',
    what: 'This route will connect one canonical meeting to notices, agenda items, packets, statements, decisions, media, and follow-up.',
    source: 'Current direct records plus a future explicit meeting-to-record relationship projection.',
    filedUnder: 'Civic records · Meeting detail',
    review: 'Direct records remain labelled unscoped until a stable meeting relationship is supplied.',
    lifecycle: 'Current state: relationship gap with direct authorized records only.',
    limits: 'A date, agenda ID, title, or source mention does not prove that a record belongs to this meeting.',
    expectedResult: 'A complete meeting history with official identifiers, packet versions, agenda order, decisions, media, and exact receipts.',
  },
  'cards-overview': {
    label: 'About the reviewed Cards view',
    what: 'Cards exposes the shared reviewer records with trust, AI/fact separation, completeness, and expandable source evidence.',
    source: 'The authorized reviewer response and shared record renderer.',
    filedUnder: 'Research · Reviewed record cards',
    review: 'No card renders outside the reviewer lane; loading/error states replace stale content.',
    lifecycle: 'Current state: live private record view with explicit demo states only when requested.',
    limits: 'Cards do not create typed events, issues, meetings, officials, scores, or public publication rights.',
    expectedResult: 'A reusable evidence card whose every field, source, gap, and correction can be inspected.',
  },
  'legacy-timeline-overview': {
    label: 'About the legacy Timeline view',
    what: 'This compatibility route shows the older reviewed-card chronology and trust/source interactions.',
    source: 'The same authorized reviewer response or an explicitly requested visual-test fixture.',
    filedUnder: 'Timeline · Compatibility view',
    review: 'It must preserve the same access and evidence rules as the canonical Timeline.',
    lifecycle: 'Current state: supported compatibility route; the canonical research surface is /timeline.',
    limits: 'The legacy layout does not define new data semantics or bypass missing typed event fields.',
    expectedResult: 'A controlled migration path until all consumers use the canonical Timeline without losing evidence behavior.',
  },
} as const satisfies Record<string, InfoNoteDefinition>;

export type PrivateInfoNoteId = keyof typeof PRIVATE_INFO_NOTES;
